language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - composer global require "hirak/prestissimo:^0.2"
  - composer install --prefer-source --no-interaction
  - phpenv config-add xdebug.ini

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover