language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo

install:
  - composer install --prefer-source --no-interaction

before_script:
  - phpenv config-add /tmp/xdebug.ini

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover